modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"

[[mods]]
modId = "rayon_entity"
version = "${version}"
displayName = "Rayon Entity"
authors = "Lazurite Team"
description = "The entity API for Rayon."
logoFile = "icon.png"

[[dependencies.rayon_entity]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rayon_entity]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"
